# gcloud deployment-manager deployments create setup-apis --config setup-apis.yaml --preview

imports:
- path: enable-api-template.py
- path: create-bucket-template.py
- path: create-bigquery-dataset-template.py

resources:
#enable api:s
- name: pubsub-api
  type: enable-api-template.py
  properties:
    api: pubsub.googleapis.com

- name: dataflow-api
  type: enable-api-template.py
  properties:
    api: dataflow.googleapis.com

- name: compute-api
  type: enable-api-template.py
  properties:
    api: compute.googleapis.com

- name: cloudbuild-api
  type: enable-api-template.py
  properties:
    api: cloudbuild.googleapis.com