# Copyright (C) 2018 - 2019 Robert Sahlin
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# gcloud deployment-manager deployments create setup-processor --config setup-processor-resources.yaml

imports:
- path: create-bucket-template.py
- path: create-bigquery-dataset-template.py

resources:
- name: processor-bucket
  type: create-bucket-template.py
  properties:
    location: europe-west1
    bucketSuffix: -processor
- name: bigquery-streams-dataset
  type: create-bigquery-dataset-template.py
  properties:
    streamId: streams
    location: EU
- name: bigquery-backup-dataset
  type: create-bigquery-dataset-template.py
  properties:
    streamId: backup
    location: EU